spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=asistencia;encrypt=true;trustServerCertificate=true}
    username: ${DB_USER:sa}
    password: ${DB_PASS:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true